"use client"

import NextPage from "next"
import React, { useState } from "react"
import Head from "next/head"
//import Image from 'next/image'


import {
  Flex,
  Navbar,
  Heading,
  Footer,
  FooterCopyright,
  SFImage,
  PopupModal
} from "@/components";

import { Avator, Name, UserName } from "@/components/AppComponent";
import { TopBanner } from "@/components/TopPopup";

// Page Sections


import {
  ProfileCard
} from "@/sections";



export default function Home() {

  return (
    <div>
      <Head>
        <title>Shota Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBanner>現在このWebページは開発中です。</TopBanner>
      <Navbar>Shota's Portfolio</Navbar>      
      <div className="container mx-auto">
      <ProfileCard>
        <h1>Shota Shimazu</h1>
      </ProfileCard>
      </div>
      { /* <StorySection stories={stories}/> */}
      
      { /*
      <Works />
      <Writings />
      <SkillsSection />
      <SocialSection />
        */ }
      <Footer>
        <FooterCopyright />
      </Footer>
    </div>
  );
};

