"use client";

import NextPage from "next";
import React, { useState } from "react";
import Head from "next/head";
//import Image from 'next/image'

import {
  Flex,
  Navbar,
  Heading,
  Footer,
  FooterCopyright,
  SFImage,
  PopupModal,
} from "@/components";

import { Avator, Name, UserName } from "@/components/AppComponent";
import { TopBanner } from "@/components/TopPopup";

// Page Sections

import { ProfileCard } from "@/sections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shota Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBanner>現在このWebページは開発中です。表示内容が異なる場合がございます。</TopBanner>
      <div className="container mx-auto">
      <Navbar>Shota's Portfolio</Navbar>

        <div className="grid grid-cols-2 gap-4 grid-flow-row auto-rows-max md:auto-rows-min">
          <ProfileCard className="w-16 md:w-32 ">
          </ProfileCard>
          <div className="md:max-lg:flex">
            <h1>SSSSSS</h1>
          </div>
          <ProfileCard className="w-16 md:w-32 ">
            <h1>Shota Shimazu</h1>
          </ProfileCard>{" "}
        </div>
      </div>
      {/* <StorySection stories={stories}/> */}

      {/*
      <Works />
      <Writings />
      <SkillsSection />
      <SocialSection />
        */}
      <Footer>
        <FooterCopyright />
      </Footer>
    </div>
  );
}
